USE [master]
GO

/****** Object:  Database [STUDIO]    Script Date: 5/25/2024 3:10:36 PM ******/
CREATE DATABASE [STUDIO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'STUDIO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\STUDIO.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'STUDIO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\STUDIO_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [STUDIO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [STUDIO] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [STUDIO] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [STUDIO] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [STUDIO] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [STUDIO] SET ARITHABORT OFF 
GO

ALTER DATABASE [STUDIO] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [STUDIO] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [STUDIO] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [STUDIO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [STUDIO] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [STUDIO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [STUDIO] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [STUDIO] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [STUDIO] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [STUDIO] SET  ENABLE_BROKER 
GO

ALTER DATABASE [STUDIO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [STUDIO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [STUDIO] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [STUDIO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [STUDIO] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [STUDIO] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [STUDIO] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [STUDIO] SET RECOVERY FULL 
GO

ALTER DATABASE [STUDIO] SET  MULTI_USER 
GO

ALTER DATABASE [STUDIO] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [STUDIO] SET DB_CHAINING OFF 
GO

ALTER DATABASE [STUDIO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [STUDIO] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [STUDIO] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [STUDIO] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [STUDIO] SET QUERY_STORE = OFF
GO

ALTER DATABASE [STUDIO] SET  READ_WRITE 
GO

